version: '3.8'

services:
  web:
    # image: mommu-docker
    image: odoo-post
    # build: 
    #   context: .
    #   dockerfile: Dockerfile
    # container_name: odoo16-web
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ../../:/mnt/extra-addons
      - ./config:/etc/odoo
      - ./odoo_logs:/var/log/odoo
    # environment:
    #   - HOST=db
    #   - USER=odoo
    #   - PASSWORD=odoo
    #   - POSTGRES_DB=postgres
    command: sleep infinity  # Keep the container running to interact with it

    # command: python3 /odoo/odoo-bin -d postgres --db-user odoo --db-password odoo --db-host db --db-port 5432



  db:
    image: postgres:13
    container_name: odoo16-db
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

volumes:
  odoo-web-data:
  odoo-db-data:
