name: Odoo Module CI

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: odoo
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U odoo -d odoo"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Odoo
      run: |
        wget https://nightly.odoo.com/14.0/nightly/src/odoo_14.0.latest.tar.gz
        tar -xzf odoo_14.0.latest.tar.gz
        mv odoo-14.0 odoo

    - name: Install custom module
      run: |
        mkdir -p odoo/custom_addons
        cp -r custom_addons/your_module odoo/custom_addons/

    - name: Lint with pylint
      run: |
        pip install pylint
        pylint custom_addons/your_module --load-plugins=pylint_odoo

    - name: Run tests
      env:
        PGHOST: 127.0.0.1
        PGPORT: 5432
        PGUSER: odoo
        PGPASSWORD: odoo
        PGDATABASE: odoo
      run: |
        cd odoo
        python odoo-bin --addons-path=custom_addons -d test_db --stop-after-init --init=your_module --test-enable

    - name: Postgres logs (for debugging)
      if: failure()
      run: docker logs postgres

