name: Lint Odoo Code

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Load Docker image from cache or build if not available
      run: |
        docker pull salras/odoo-base

    - name: Run Pylint with Odoo Plugin
      continue-on-error: true
      run: |
        # Add the directory as safe before mounting it in Docker
        git config --global --add safe.directory /mnt/
        
        # Run the Docker container and mount the directory
        docker run --rm -v $(pwd):/mnt/ salras/odoo-base pylint --load-plugins=pylint_odoo -d all -e odoolint /mnt/
